default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: sam
  password: samiralak
  pool: 20

development:
  <<: *default
  database: novel_development

test:
  <<: *default
  database: novel_test

production:
  <<: *default
  database: novel_production
