default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: masud	
  pool: 20

development:
  <<: *default
  password: Openpostgres1!
  database: novel_development

test:
  <<: *default
  password: Openpostgres1!
  database: novel_test

production:
  <<: *default
  database: novel_production
